/**
 * Common stylesheets and styling related constants
 */

export const COLOR_PALETTE = {
  white: "#FFFFFF",
  red: "#FF0000",
  green: "#00FF00",
  blue: "#0000FF",
  magenta: "#FF00FF",
  cyan: "#00FFFF",
  yellow: "#FFFF00",
  black: "#000000",
  aquamarine: "#70DB93",
  bakersChocolate: "#5C3317",
  blueViolet: "#9F5F9F",
  brass: "#B5A642",
  brightGold: "#D9D919",
  brown: "#A62A2A",
  bronze: "#8C7853",
  bronzeII: "#A67D3D",
  cadetBlue: "#5F9F9F",
  coolCopper: "#D98719",
  copper: "#B87333",
  coral: "#FF7F00",
  cornFlowerBlue: "#42426F",
  darkBrown: "#5C4033",
  darkGreen: "#2F4F2F",
  darkGreenCopper: "#4A766E",
  darkOliveGreen: "#4F4F2F",
  darkOrchid: "#9932CD",
  darkPurple: "#871F78",
  darkSlateBlue: "#6B238E",
  darkSlateGrey: "#2F4F4F",
  darkTan: "#97694F",
  darkTurquoise: "#7093DB",
  darkWood: "#855E42",
  dimGrey: "#545454",
  dustyRose: "#856363",
  feldspar: "#D19275",
  firebrick: "#8E2323",
  flesh: "#F5CCB0",
  forestGreen: "#238E23",
  gold: "#CD7F32",
  goldenrod: "#DBDB70",
  grey: "#C0C0C0",
  greenCopper: "#527F76",
  greenYellow: "#93DB70",
  hunterGreen: "#215E21",
  indianRed: "#4E2F2F",
  khaki: "#9F9F5F",
  lightBlue: "#C0D9D9",
  lightGrey: "#A8A8A8",
  lightSteelBlue: "#8F8FBD",
  lightWood: "#E9C2A6",
  limeGreen: "#32CD32",
  mandarianOrange: "#E47833",
  maroon: "#8E236B",
  mediumAquamarine: "#32CD99",
  mediumBlue: "#3232CD",
  mediumForestGreen: "#6B8E23",
  mediumGoldenrod: "#EAEAAE",
  mediumOrchid: "#9370DB",
  mediumSeaGreen: "#426F42",
  mediumSlateBlue: "#7F00FF",
  mediumSpringGreen: "#7FFF00",
  mediumTurquoise: "#70DBDB",
  mediumVioletRed: "#DB7093",
  mediumWood: "#A68064",
  midnightBlue: "#2F2F4F",
  navyBlue: "#23238E",
  neonBlue: "#4D4DFF",
  neonPink: "#FF6EC7",
  newMidnightBlue: "#00009C",
  newTan: "#EBC79E",
  oldGold: "#CFB53B",
  orange: "#FF7F00",
  orangeRed: "#FF2400",
  orchid: "#DB70DB",
  paleGreen: "#8FBC8F",
  pink: "#BC8F8F",
  plum: "#EAADEA",
  quartz: "#D9D9F3",
  richBlue: "#5959AB",
  salmon: "#6F4242",
  scarlet: "#8C1717",
  seaGreen: "#238E68",
  semiSweetChocolate: "#6B4226",
  sienna: "#8E6B23",
  silver: "#E6E8FA",
  skyBlue: "#3299CC",
  slateBlue: "#007FFF",
  spicyPink: "#FF1CAE",
  springGreen: "#00FF7F",
  steelBlue: "#236B8E",
  summerSky: "#38B0DE",
  tan: "#DB9370",
  thistle: "#D8BFD8",
  turquoise: "#ADEAEA",
  veryDarkBrown: "#5C4033",
  veryLightGrey: "#CDCDCD",
  violet: "#4F2F4F",
  violetRed: "#CC3299",
  wheat: "#D8D8BF",
  yellowGreen: "#99CC32",
}

export const COLOR_LIST = [
  COLOR_PALETTE.white,
  COLOR_PALETTE.red,
  COLOR_PALETTE.green,
  COLOR_PALETTE.blue,
  COLOR_PALETTE.magenta,
  COLOR_PALETTE.cyan,
  COLOR_PALETTE.yellow,
  COLOR_PALETTE.black,
  COLOR_PALETTE.aquamarine,
  COLOR_PALETTE.bakersChocolate,
  COLOR_PALETTE.blueViolet,
  COLOR_PALETTE.brass,
  COLOR_PALETTE.brightGold,
  COLOR_PALETTE.brown,
  COLOR_PALETTE.bronze,
  COLOR_PALETTE.bronzeII,
  COLOR_PALETTE.cadetBlue,
  COLOR_PALETTE.coolCopper,
  COLOR_PALETTE.copper,
  COLOR_PALETTE.coral,
  COLOR_PALETTE.cornFlowerBlue,
  COLOR_PALETTE.darkBrown,
  COLOR_PALETTE.darkGreen,
  COLOR_PALETTE.darkGreenCopper,
  COLOR_PALETTE.darkOliveGreen,
  COLOR_PALETTE.darkOrchid,
  COLOR_PALETTE.darkPurple,
  COLOR_PALETTE.darkSlateBlue,
  COLOR_PALETTE.darkSlateGrey,
  COLOR_PALETTE.darkTan,
  COLOR_PALETTE.darkTurquoise,
  COLOR_PALETTE.darkWood,
  COLOR_PALETTE.dimGrey,
  COLOR_PALETTE.dustyRose,
  COLOR_PALETTE.feldspar,
  COLOR_PALETTE.firebrick,
  COLOR_PALETTE.flesh,
  COLOR_PALETTE.forestGreen,
  COLOR_PALETTE.gold,
  COLOR_PALETTE.goldenrod,
  COLOR_PALETTE.grey,
  COLOR_PALETTE.greenCopper,
  COLOR_PALETTE.greenYellow,
  COLOR_PALETTE.hunterGreen,
  COLOR_PALETTE.indianRed,
  COLOR_PALETTE.khaki,
  COLOR_PALETTE.lightBlue,
  COLOR_PALETTE.lightGrey,
  COLOR_PALETTE.lightSteelBlue,
  COLOR_PALETTE.lightWood,
  COLOR_PALETTE.limeGreen,
  COLOR_PALETTE.mandarianOrange,
  COLOR_PALETTE.maroon,
  COLOR_PALETTE.mediumAquamarine,
  COLOR_PALETTE.mediumBlue,
  COLOR_PALETTE.mediumForestGreen,
  COLOR_PALETTE.mediumGoldenrod,
  COLOR_PALETTE.mediumOrchid,
  COLOR_PALETTE.mediumSeaGreen,
  COLOR_PALETTE.mediumSlateBlue,
  COLOR_PALETTE.mediumSpringGreen,
  COLOR_PALETTE.mediumTurquoise,
  COLOR_PALETTE.mediumVioletRed,
  COLOR_PALETTE.mediumWood,
  COLOR_PALETTE.midnightBlue,
  COLOR_PALETTE.navyBlue,
  COLOR_PALETTE.neonBlue,
  COLOR_PALETTE.neonPink,
  COLOR_PALETTE.newMidnightBlue,
  COLOR_PALETTE.newTan,
  COLOR_PALETTE.oldGold,
  COLOR_PALETTE.orange,
  COLOR_PALETTE.orangeRed,
  COLOR_PALETTE.orchid,
  COLOR_PALETTE.paleGreen,
  COLOR_PALETTE.pink,
  COLOR_PALETTE.plum,
  COLOR_PALETTE.quartz,
  COLOR_PALETTE.richBlue,
  COLOR_PALETTE.salmon,
  COLOR_PALETTE.scarlet,
  COLOR_PALETTE.seaGreen,
  COLOR_PALETTE.semiSweetChocolate,
  COLOR_PALETTE.sienna,
  COLOR_PALETTE.silver,
  COLOR_PALETTE.skyBlue,
  COLOR_PALETTE.slateBlue,
  COLOR_PALETTE.spicyPink,
  COLOR_PALETTE.springGreen,
  COLOR_PALETTE.steelBlue,
  COLOR_PALETTE.summerSky,
  COLOR_PALETTE.tan,
  COLOR_PALETTE.thistle,
  COLOR_PALETTE.turquoise,
  COLOR_PALETTE.veryDarkBrown,
  COLOR_PALETTE.veryLightGrey,
  COLOR_PALETTE.violet,
  COLOR_PALETTE.violetRed,
  COLOR_PALETTE.wheat,
  COLOR_PALETTE.yellowGreen,
]